name: workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
          

      - name: Welcome Message
        run: echo Testing
      - name: List Files
        run: ls
      - name: Read Files
        run: cat README.md