name: workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Files
        run: |
         echo Testing
         ls -ltra
         cat README.md
      