name: Matrix Configuration
on: 
  push: 
  workflow_dispatch: 
jobs:
  deploy_on_ubuntu:
      runs-on: ubuntu-latest
      steps:
        - name: Echo docker detail
          run: docker info
        - name: Running Hello WOrld
          run: docker run --help
          