name: Generate ASCII Framework
on: 
    push: 
    workflow_dispatch: 
jobs:
    Building_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses:  actions/checkout@v4
            - name: Installing COWSAY package
              run: sudo apt-get install cowsay -y
            - name: Execute COWSAY CMD
              run: cowsay -f dragon "Iam a dragon ... Run for your life" >> dragon.txt
            - name: Test File Exists
              run: grep -i dragon "dragon.txt"
            - name: List Files
              run: ls -ltra
            - name: Read FIles
              run: cat dragon.txt
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt
    test_job_1:
        runs-on: ubuntu-latest
        needs: Building_job_1
        steps:
          - name: Download Artificats
            uses: actions/download-artifact@v4
            with:
              name: dragon-text-file
          - name: Detcting files
            run: grep -i "dragon" dragon.txt
    deploy_job_1:
        runs-on: ubuntu-latest
        needs: test_job_1
        steps:
          - name: Download Artificats
            uses: actions/download-artifact@v4
            with:
              name: dragon-text-file
            
          - name: Checking files
            run: cat dragon.txt
          - name: Deployin
            run: echo "Deploying"....

                  