name: Generate ASCII Framework
on: 
    push: 
    workflow_dispatch: 
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses:  actions/checkout@v4
            - name: Install COWSAY Program
              run: sudo apt-get install cowsay -y
            - name: Execute COWSAY CMD
              run: cowsay -f cow "Iam a COW ... Run for your life" >> dragon.txt
            - name: Test File Exists
              run: grep -i dragon "dragon.txt"
            - name: List Files
              run: ls -ltra
            - name: Read FIles
              run: cat dragon.txt

                  